# Generated by Django 5.0.7 on 2024-07-26 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demographic',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.search'),
        ),
        migrations.AddField(
            model_name='populationdata',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.zone'),
        ),
        migrations.AddField(
            model_name='interestzonecount',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.zone'),
        ),
        migrations.AddField(
            model_name='demographic',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.zone'),
        ),
        migrations.AddField(
            model_name='busyness',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.zone'),
        ),
        migrations.AddField(
            model_name='billboard',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.zone'),
        ),
        migrations.AddField(
            model_name='advertisinglocation',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='populationdata',
            unique_together={('zone', 'age_category')},
        ),
        migrations.AlterUniqueTogether(
            name='interestzonecount',
            unique_together={('zone', 'interest')},
        ),
        migrations.AlterUniqueTogether(
            name='demographic',
            unique_together={('zone', 'search')},
        ),
        migrations.AlterUniqueTogether(
            name='busyness',
            unique_together={('datetime', 'zone')},
        ),
    ]
