# Generated by Django 5.0.6 on 2024-06-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_agecategory_remove_search_max_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='search',
            name='target_market_interests',
        ),
        migrations.AddField(
            model_name='search',
            name='target_market_interests',
            field=models.ManyToManyField(to='myapp.interest'),
        ),
    ]
