# Generated by Django 5.0.6 on 2024-06-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_interest_remove_search_target_market_interests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='id',
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
