# Generated by Django 5.0.6 on 2024-06-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_interest_id_alter_interest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='target_market_interests',
        ),
        migrations.AddField(
            model_name='search',
            name='target_market_interests',
            field=models.CharField(default=32, max_length=255),
            preserve_default=False,
        ),
    ]
