# Generated by Django 5.0.6 on 2024-06-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_search_target_market_interests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='target_market_interests',
        ),
        migrations.AddField(
            model_name='search',
            name='target_market_interests',
            field=models.ManyToManyField(to='myapp.interest'),
        ),
    ]
