# Generated by Django 5.0.6 on 2024-06-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_search_date_of_advertising_search_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='demographic',
            unique_together={('zone', 'search')},
        ),
        migrations.RemoveField(
            model_name='demographic',
            name='datetime',
        ),
    ]
