# Generated by Django 5.0.6 on 2024-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_creditusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='free_search',
            field=models.BooleanField(default=False),
        ),
    ]
