# Generated by Django 5.0.6 on 2024-07-22 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_customuser_free_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='free_search',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AdvertisingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('format', models.CharField(blank=True, max_length=255, null=True)),
                ('category_alias', models.CharField(blank=True, max_length=255, null=True)),
                ('market', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('design_template_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('calculated_cpm', models.FloatField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('cost_per_day', models.FloatField(blank=True, null=True)),
                ('numbers_total', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.zone')),
            ],
        ),
    ]
