# Generated by Django 5.0.6 on 2024-07-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_customuser_free_search_advertisinglocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisinglocation',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisinglocation',
            name='property_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
