# Generated by Django 5.0.7 on 2024-07-26 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('boundary_coordinates', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=255)),
                ('sign_illumination', models.CharField(max_length=255)),
                ('sign_sq_footage', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.zone')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('format', models.CharField(blank=True, max_length=255, null=True)),
                ('category_alias', models.CharField(blank=True, max_length=255, null=True)),
                ('market', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('design_template_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('calculated_cpm', models.FloatField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('cost_per_day', models.FloatField(blank=True, null=True)),
                ('numbers_total', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('property_id', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.zone')),
            ],
        ),
        migrations.CreateModel(
            name='PopulationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField()),
                ('age_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.agecategory')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.zone')),
            ],
            options={
                'unique_together': {('zone', 'age_category')},
            },
        ),
        migrations.CreateModel(
            name='InterestZoneCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.interest')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.zone')),
            ],
            options={
                'unique_together': {('zone', 'interest')},
            },
        ),
    ]
