name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get current timestamp
      id: vars
      run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"

    - name: Build Docker image
      run: docker build -t NY_app:${{ steps.vars.outputs.timestamp }} .

    - name: Run tests
      run: docker run NY_app:${{ steps.vars.outputs.timestamp }} test-command

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to VM
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        VM_HOST: ${{ secrets.VM_HOST }}
        VM_USER: ${{ secrets.VM_USER }}
        IMAGE_TAG: ${{ steps.vars.outputs.timestamp }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST "docker load < <(docker save NY_app:$IMAGE_TAG)"
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST "docker-compose -f ~/Summer_Project/New-York-App/docker-compose.yaml up -d"
