name: Pylint

on:
  push:
    branches: 
      - '**' 
  pull_request:
    branches:
      - '**'  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint nbconvert nbqa

    - name: Convert Notebooks and Run Pylint
      run: |
        # Convert notebooks to Python scripts
        for notebook in $(git ls-files '*.ipynb'); do
          jupyter nbconvert --to script "$notebook"
        done
        
        # Run Pylint on both .py files and converted notebooks
        pylint $(git ls-files '*.py') $(git ls-files '*.ipynb' | sed 's/.ipynb$/.py/')

    - name: Clean up converted notebook scripts
      run: |
        # Remove converted Python scripts from notebooks
        rm -f $(git ls-files '*.ipynb' | sed 's/.ipynb$/.py/')
