name: Pylint

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint nbconvert nbqa

    - name: Get list of changed files
      id: changed-files
      run: |
        CHANGED_FILES=$(git diff --name-only ${{ github.sha }}^1 ${{ github.sha }} -- '*.py' '*.ipynb')
        echo "::set-output name=files::$CHANGED_FILES"

    - name: Convert Notebooks to Python Scripts
      if: steps.changed-files.outputs.files
      run: |
        for notebook in $(echo "${{ steps.changed-files.outputs.files }}" | grep '.ipynb'); do
          jupyter nbconvert --to script "$notebook"
        done

    - name: Run Pylint on changed files
      if: steps.changed-files.outputs.files
      run: |
        FILES=$(echo "${{ steps.changed-files.outputs.files }}" | grep '.py' | tr '\n' ' ')
        if [ -n "$FILES" ]; then
          pylint $FILES
        fi

    - name: Clean up converted notebook scripts
      if: steps.changed-files.outputs.files
      run: |
        for notebook in $(echo "${{ steps.changed-files.outputs.files }}" | grep '.ipynb'); do
          rm -f "${notebook%.ipynb}.py"
        done
